config/routes.rb
Rails.application.routes.draw do
  

  

  

  resources :reason_for_comings
  get 'care_giver_return_equipments/index'

  get 'care_giver_return_equipments/edit'

  get 'care_giver_return_equipments/new'

  resources :care_giver_equipments
  resources :care_giver_daily_attendances do
    collection do
      get :all_routes
      get :news
      get :today_attendance
      post :attendance
      post :update_attendance
      post :save_attendance
      post :attendance_of_cg
      get :payroll
      post :today_patients
      post :start
      post :care_giver_profile
      post :patient_care_giver_profile
      post :enquiries
      post :amount
      get :cg_attendance_in_date_range
    end
  end


  get 'track_vitals/index'

  get 'count_enquiry_managements/index'
  get 'count_enquiry_managements/all_cities'
  get 'count_enquiry_managements/all_jsons'
  

  resources :reports do
    collection do 
      post :get_report
      get :balance
      post :balance_report
      get :payment_received
      post :payment_report
      get :invoice
      post :invoice_details
      get :credit_notes
      post :credit
      get :due_date
      get :age_report
    end
  end
  
  get 'requested_services/index'

  get 'patient_disabilities/index'

  get 'time_of_administrations/index'

  resources :user_creations do
    collection do
      get :all_users
      post :save_user
      put :update_user
      delete :delete_user
    end
  end

  resources :role_creations do
    collection do
      get :menu_bar
      post :save_menu
      post :get_menu
      get :role
      get :role_menu
      post :corresponding_menu
      post :update_menu
      delete :delete_role
    end
  end
  get 'patient_rate_masters/index'

  get 'daily_checks/index'

  get 'care_giver_documents/index'

  resources :application_defaults do
    collection do 
      get :cg_price_ranges
    end
  end


  get 'patients/index'

  get 'patients/show'

  get 'unit_masters/index'

  get 'route_masters/index'

  get 'form_masters/index'

  get 'routine_masters/index'

  get 'unit_masters/index'

  get 'route_masters/index'

  get 'form_masters/index'

  get 'routine_masters/index'

  get 'patients_care_plans/index'

  get 'patient_care_plan/index'

  get 'vital_trends/index'

  get 'key_vitals_masters/index'


  get 'drug_quantity_masters/index'

  get 'care_to_be_provided_plans/index'

  resources :transport_charge_masters do
    collection do
      get :charge_for_distance
    end
  end

  resources :city_masters do
    collection do
      post :save_city
      get :check_city_support
      post :check_location_support
    end
    resources :area_masters
  end

  resources :care_giver_enquiries do
    collection do
      get :approval_list
      get :cg
      get :cg_city_request
      get :approved
      get :closed
      get :new_city_request
      get :hold
      get :recruitment
      post :new_city
      post :create_enquiry
    end
    member do
      put :update_enq
      put :recruit
      put :holding
      get :cg_appointment
      get :appointment
      put :close
      get :dispatch_cg_from_recruit_list
    end
  end
  
  resources :care_giver_masters do
    collection do
      post :cg_enquiries
      get :care_giver_enquiry
      get :attendance
      get :daily_attendance
      get :location
      get :enquiry
      post :init_enquiry
      get :from_to_date
      post :patients 
      get :payroll
      get :get_caregivers        
      get :get_caregivers_for_transfer   
    end
    member do
      put :finish
      get :cg_appointment
      get :primary_registraion
      put :update_job_type      
      put :update_status
      get :select_job_type
      get :approval_list
      get :month_plan      
      get :leave_pre_approval_check
      post :update_leave_of_cg
      put :update_cg_stay
    end
    
    resources :care_giver_return_equipments do
      collection do
        post :save_equipments
      end
    end
    
    resources :care_giver_additional_details do
      member do 
        put :approve_physical_description
        put :approve_helth_and_life
      end
      collection do
        get :health_and_lefe_style
        get :physical_description
        post :save_additional_details
      end
    end

    resources :care_giver_relatives do
      member do 
        put :approve
      end
    end

    resources :care_giver_services do
      collection do 
        get :services_for_registration
        post :save_services
        put :approve
      end
    end
    resources :care_giver_educations do
      member do 
        put :approve
      end

      collection do 
        get :cg_dob
        get :education_for_registration
        post :save_education
      end
    end
    
    resources :care_giver_documents do
      member do 
        put :approve
      end

      collection do 
        get :document_for_upload
        post :save_document
      end
    end

    resources :care_giver_employers do
      member do 
        put :approve
      end

      collection do 
        get :employer_for_registration
        post :save_employer
        post :save_fresher
      end
    end

    resources :care_giver_charges do
      member do 
        put :approve
      end

      collection do 
        get :new_or_existing_charges
        post :save_charges
      end
    end
    resources :care_giver_availability_masters
    resources :care_giver_leaves do
      member do 
        put :approve
        put :reject
      end
    end
  end

  get "care_giver_leaves/all_cg_leaves" => "care_giver_leaves#all_cg_leaves"
  
  resources :enquiries do
    collection do
      put :update_to_audit
      get :edit_values
      get :all_appointments
      get :appointments
      post :enquiry_details
      get :landing
      get :init_enquiry
      put :update_approach
      get :service_request
      put :update_service_request
      get :care_givers
      post :init_request
      post :list_care_givers
      post :book_care_giver
      get :new_appointment_for_enquiry
      post :create_appointment_for_enquiry
      post :capture_customer_on_empty_results
      get :new_city
      get :new_enquiry_from_missed_call_request
      get :missed_call_requests
      put :update_appointment
    end
    member do
      put :update_appointment_status
      get :appointment_edit
      put :update_appointment
      put :close
      post :check_cg_availability_on_modified_query
      get :show_appointment_for_enquiry
      post :update_pre_enquiry
    end
    
  end
  
  resources :enrollments do
    collection do
      get :reason_for_coming
      get :super_care_giver
      get :pcp
      get :cg_transfer
      post :save_disabilities
    end
    member do
      get :save_patients
      get :patient_edit
      get :change_care_giver      
      post :update_care_giver_change
      post :compare_payments_on_cg_change
      get :transfer_care_giver
      post :update_care_giver_transfer
      post :compare_payments_on_cg_transfer
      get :change_plan
      post :update_change_plan
      get :new_notification
      patch :post_notification
      get :close      
      patch :save_close
      
    end
    
    collection do
      get :incomplete_pcp
      get :closed_form
    end
    
    resources :payment_masters do
      member do
        get :payment_preview
        put :revoke_credit_note
        put :issue_credit_note
        put :update_credit_note_status
        delete :destroy_credit_note
        post :create_credit_note
        put :mark_as_pending_credit_note
        put :update_payment_discount_details
        post :recalculate
        get :credit_notes
      end

      collection do
        post :new_recurring_payment
        post :recurring_payment
        get :revise_care_giver_charge
        get :review_invoices
        get :payment_on_closing_enrollment
        post :save_closing_payment
      end
      
      resources :payment_bills
    end

    resource :patient_care_plan
    
    resource :patients_care_plans do
      collection do
        get :pcp_pdf
        get :all_jsons
      end
    end
    
    resources :track_vitals
    
    resources :patient_adaptive_equipments do
      collection do
        post :save_patient_equipments
      end
    end   
          
    resources :patient_disabilities do
      collection do
        post :save_patient_disabilities
      end
    end  
    
    resources :requested_services do
      collection do
        post :save_requested_services
        get :enrolled
      end
    end  
    
    resources :patient_selfcare_abilities
 
    resources :care_to_be_provided_plans do 
      collection do
         get :get_care_to_be_provided_plans
      end
    end
    
    resources :drug_quantity_masters do
     get :autocomplete_drug_master_names, :on => :collection
    end
    
    resources :vital_trends
        
    resources :patient_routines do
      collection do
        put :update_patient_routine
      end
    end
    
  end

  
  
  resources :service_masters do
    resources :sub_service_masters do
      collection do
        get :all_sub_services
      end
    end
  end
  
  get "sub_service_masters/all_sub_services" => "sub_service_masters#all_sub_services"
  
  get "/enrollments/:enrollment_id/payment_bills/enrollment_bills" => 'payment_bills#enrollment_bills'
  get "/enquiries/:enquiry_id/enrollments/new" => 'enrollments#new'
  post "/enquiries/:enquiry_id/enrollments" => 'enrollments#create'
  post "/enquiries/:enquiry_id/enrollments/safety_measures" => 'enrollments#safety_measures'
  
  # get '/enrollments/:enrollment_id/payment_masters' => 'payment_masters#index'
  # get '/enrollments/:enrollment_id/payment_masters/new' => 'payment_masters#new'
  # post '/enrollments/:enrollment_id/payment_masters' => 'payment_masters#create'
  # post '/enrollments/:enrollment_id/payment_masters/new_recurring_payment' => 'payment_masters#new_recurring_payment'

app/models/payment_bill.rb
class PaymentBill < ActiveRecord::Base
  attr_accessor :total_amount_to_pay
  belongs_to :payment_master
  
  scope :completed, lambda{ where("status = 'COMPLETED'")}

  def bill_pre_process_and_save
    ActiveRecord::Base.transaction do
      if amount_paid == total_amount_to_pay.to_i 
        payment_master.mark_as_paid
      elsif amount_paid > total_amount_to_pay.to_i
        payment_master.mark_as_paid
        credit_note = CreditNote.new do |cr|
          cr.payment_master = payment_master
          cr.reason_for_creadit_note = CreditNote::EXESS_PAID_MSG
          cr.value_of_credit_note = (amount_paid - total_amount_to_pay.to_i)
          cr.credit_note_date = self.payment_date
          cr.status = "PENDING"
          cr.enrollment_id = payment_master.enrollment_id
        end
        credit_note.save
      elsif amount_paid < total_amount_to_pay.to_i
        payment_master.mark_as_partly_paid
      end
      self.status = "COMPLETED"
      self.save
    end
  end

end

app/controllers/payment_bills_controller.rb
class PaymentBillsController < ApplicationController
  before_action :load_enrollment
  before_action :load_payment_master, :except => [:enrollment_bills]
  before_action :set_payment_bill, only: [:show, :edit, :update, :destroy]


  def enrollment_bills
    @payment_bills = @enrollment.payment_masters.map(&:payment_bills).flatten
  end
  
  # GET /payment_bills
  # GET /payment_bills.json
  def index
    @payment_bills = @payment_master.payment_bills.all
  end

  # GET /payment_bills/1
  # GET /payment_bills/1.json
  def show
  end

  # GET /payment_bills/new
  def new
    @payment_bill = PaymentBill.new
    @payment_bill.payment_master_id = @payment_master.id
    if(@payment_master.payment_bills.present?)
      @payment_bill.total_amount_to_pay = @payment_master.total_pending_payment
    else
      @payment_bill.total_amount_to_pay = @payment_master.total_amount
    end
    @payment_bill.payment_date = Date.today
  end

  # GET /payment_bills/1/edit
  def edit
  end

  # POST /payment_bills
  # POST /payment_bills.json
  def create
    @payment_bill = PaymentBill.new(payment_bill_params)
    respond_to do |format|
      if @payment_bill.bill_pre_process_and_save
        format.html { redirect_to enrollment_payment_master_path(@enrollment, @payment_master), notice: 'Payment bill was successfully created.' }
        format.json { render :show, status: :created, location: @payment_bill }
      else
        format.html { render :new }
        format.json { render json: @payment_bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payment_bills/1
  # PATCH/PUT /payment_bills/1.json
  def update
    respond_to do |format|
      if @payment_bill.update(payment_bill_params)
        format.html { redirect_to @payment_bill, notice: 'Payment bill was successfully updated.' }
        format.json { render :show, status: :ok, location: @payment_bill }
      else
        format.html { render :edit }
        format.json { render json: @payment_bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payment_bills/1
  # DELETE /payment_bills/1.json
  def destroy
    @payment_bill.destroy
    respond_to do |format|
      format.html { redirect_to payment_bills_url, notice: 'Payment bill was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment_bill
      @payment_bill = PaymentBill.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def payment_bill_params
      params.require(:payment_bill).permit(:payment_master_id, :amount_paid, :payment_mode, :description_1, :description_2, :payment_done_by, :payment_date, :total_amount_to_pay)
    end
    
    def load_payment_master
      @payment_master = PaymentMaster.find(params[:payment_master_id])
    end

    def load_enrollment
      @enrollment = Enrollment.find(params[:enrollment_id])
    end

end

app/helpers/payment_bills_helper.rb
module PaymentBillsHelper
end

app/views/payment_bills/_form.html.haml
= form_for @payment_bill, :url => enrollment_payment_master_payment_bills_path(@enrollment, @payment_master),:html => {:class => "sky-form"} do |f|
  = f.hidden_field :payment_master_id
  %section
    .row
      = f.label :total_amount_to_pay, :class => "label col col-2"
      .col.col-8
        %label.input
          = f.number_field :total_amount_to_pay, :readonly => true

  %section
    .row
      = f.label :amount_paid, :class => "label col col-2"
      .col.col-8
        %label.input
          = f.number_field :amount_paid, :min => 0
  %section
    .row
      = f.label :payment_mode, :class => "label col col-2"
      .col.col-8
        %label.select
          = f.select :payment_mode, options_for_select(PaymentMaster::PAYMENT_MODES)
          %i
  %section
    .row
      = f.label :description_1, :class => "label col col-2"
      .col.col-8
        %label.input
          = f.text_field :description_1
  %section
    .row
      = f.label :description_2, :class => "label col col-2"
      .col.col-8
        %label.input
          = f.text_field :description_2
  %section
    .row
      = f.label :payment_date, :class => "label col col-2"
      .col.col-8
        %label.input
          = f.text_field :payment_date, :class => "datepicker"
    %section
      .row
        .col-md-4
        .col-md-3
          = f.submit 'Save', :class => "button"

app/views/payment_bills/_payment_bills.html.haml
%table.table.table-list
  %thead
    %tr
      %th Invoice No
      %th Amount paid
      %th Payment mode
      %th Description 1
      %th Description 2
      %th Payment done by
      %th Payment date
      %th Status

  %tbody
    - payment_bills.each do |payment_bill|
      %tr
        %td= payment_bill.payment_master.invoice_no
        %td= payment_bill.amount_paid
        %td= payment_bill.payment_mode
        %td= payment_bill.description_1
        %td= payment_bill.description_2
        %td= payment_bill.payment_done_by
        %td= payment_bill.payment_date
        %td= payment_bill.status

app/views/payment_bills/edit.html.haml
%h1 Editing payment_bill

= render 'form'

= link_to 'Show', @payment_bill
\|
= link_to 'Back', enrollment_payment_master_payment_bills_path(@enrollment, @payment_master)

app/views/payment_bills/enrollment_bills.html.haml
.sky-form
  %header
    = raw "#{link_to(@enrollment.patient.name, @enrollment)} Payments"
    .pull-right
      = link_to "Back", @enrollment, :class => "button"

.col-md-12
  = render :partial => "payment_bills", :locals => {:payment_bills => @payment_bills}

app/views/payment_bills/index.html.haml
.sky-form
  %header
    = raw "#{link_to(@enrollment.patient.name, @enrollment)} Payments"
    .pull-right
      = link_to "Back", enrollment_payment_master_path(@enrollment, @payment_master), :class => "button"
.row
  = render :partial => "payment_bills", :locals => {:payment_bills => @payment_bills}

app/views/payment_bills/new.html.haml
.col-md-8
  .row.sky-form
    %header New payment bill
    = render 'form'

app/views/payment_bills/show.html.haml
%p#notice= notice

%p
  %b Payment master:
  = @payment_bill.payment_master_id
%p
  %b Amount paid:
  = @payment_bill.amount_paid
%p
  %b Payment mode:
  = @payment_bill.payment_mode
%p
  %b Description 1:
  = @payment_bill.description_1
%p
  %b Description 2:
  = @payment_bill.description_2
%p
  %b Payment done by:
  = @payment_bill.payment_done_by
%p
  %b Payment date:
  = @payment_bill.payment_date
%p
  %b Status:
  = @payment_bill.status

= link_to 'Edit', edit_payment_bill_path(@payment_bill)
\|
= link_to 'Back', payment_bills_path