config/routes.rb
      get :care_giver_enquiry
      get :attendance
      get :daily_attendance
      get :location
      get :enquiry
      post :init_enquiry
      get :from_to_date
      post :patients 
      get :payroll
      get :get_caregivers        
      get :get_caregivers_for_transfer   
    end
    member do
      put :finish
      get :cg_appointment
      get :primary_registraion
      put :update_job_type      
      put :update_status
      get :select_job_type
      get :approval_list
      get :month_plan      
      get :leave_pre_approval_check
      post :update_leave_of_cg
      put :update_cg_stay
    end
    
    resources :care_giver_return_equipments do
      collection do
        post :save_equipments
      end
    end
    
    resources :care_giver_additional_details do
      member do 
        put :approve_physical_description
        put :approve_helth_and_life
      end
      collection do
        get :health_and_lefe_style
        get :physical_description
        post :save_additional_details
      end
    end

    resources :care_giver_relatives do
      member do 
        put :approve
      end
    end

    resources :care_giver_services do
      collection do 
        get :services_for_registration
        post :save_services
        put :approve
      end
    end
    resources :care_giver_educations do
      member do 
        put :approve
      end

      collection do 
        get :cg_dob
        get :education_for_registration
        post :save_education
      end
    end
    
    resources :care_giver_documents do
      member do 
        put :approve
      end

      collection do 
        get :document_for_upload
        post :save_document
      end
    end

    resources :care_giver_employers do
      member do 
        put :approve
      end

      collection do 
        get :employer_for_registration
        post :save_employer
        post :save_fresher
      end
    end

    resources :care_giver_charges do
      member do 
        put :approve
      end

      collection do 
        get :new_or_existing_charges
        post :save_charges
      end
    end
    resources :care_giver_availability_masters
    resources :care_giver_leaves do
      member do 
        put :approve
        put :reject
      end
    end
  end

  get "care_giver_leaves/all_cg_leaves" => "care_giver_leaves#all_cg_leaves"
  
  resources :enquiries do
    collection do
      put :update_to_audit
      get :edit_values
      get :all_appointments
      get :appointments
      post :enquiry_details
      get :landing
      get :init_enquiry
      put :update_approach
      get :service_request
      put :update_service_request
      get :care_givers
      post :init_request
      post :list_care_givers
      post :book_care_giver
      get :new_appointment_for_enquiry
      post :create_appointment_for_enquiry
      post :capture_customer_on_empty_results
      get :new_city
      get :new_enquiry_from_missed_call_request
      get :missed_call_requests
      put :update_appointment
    end
    member do
      put :update_appointment_status
      get :appointment_edit
      put :update_appointment
      put :close
      post :check_cg_availability_on_modified_query
      get :show_appointment_for_enquiry
      post :update_pre_enquiry
    end
    
  end
  
  resources :enrollments do
    collection do
      get :reason_for_coming
      get :super_care_giver
      get :pcp
      get :cg_transfer
      post :save_disabilities
    end
    member do
      get :save_patients
      get :patient_edit
      get :change_care_giver      
      post :update_care_giver_change
      post :compare_payments_on_cg_change
      get :transfer_care_giver
      post :update_care_giver_transfer
      post :compare_payments_on_cg_transfer
      get :change_plan
      post :update_change_plan
      get :new_notification
      patch :post_notification
      get :close      
      patch :save_close
      
    end
    
    collection do
      get :incomplete_pcp
      get :closed_form
    end
    
    resources :payment_masters do
      member do
        get :payment_preview
        put :revoke_credit_note
        put :issue_credit_note
        put :update_credit_note_status
        delete :destroy_credit_note
        post :create_credit_note
        put :mark_as_pending_credit_note
        put :update_payment_discount_details
        post :recalculate
        get :credit_notes
      end

      collection do
        post :new_recurring_payment
        post :recurring_payment
        get :revise_care_giver_charge
        get :review_invoices
        get :payment_on_closing_enrollment
        post :save_closing_payment
      end
      
      resources :payment_bills
    end

    resource :patient_care_plan
    
    resource :patients_care_plans do
      collection do
        get :pcp_pdf
        get :all_jsons
      end
    end
    
    resources :track_vitals
    
    resources :patient_adaptive_equipments do
      collection do
        post :save_patient_equipments
      end
    end   
          
    resources :patient_disabilities do
      collection do
        post :save_patient_disabilities
      end
    end  
    
    resources :requested_services do
      collection do
        post :save_requested_services
        get :enrolled
      end
    end  
    
    resources :patient_selfcare_abilities
 
    resources :care_to_be_provided_plans do 
      collection do
         get :get_care_to_be_provided_plans
      end
    end
    
    resources :drug_quantity_masters do
     get :autocomplete_drug_master_names, :on => :collection
    end
    
    resources :vital_trends
        
    resources :patient_routines do
      collection do
        put :update_patient_routine
      end
    end
    
  end

  
  
  resources :service_masters do
    resources :sub_service_masters do
      collection do
        get :all_sub_services
      end
    end
  end
  
  get "sub_service_masters/all_sub_services" => "sub_service_masters#all_sub_services"
  
  get "/enrollments/:enrollment_id/payment_bills/enrollment_bills" => 'payment_bills#enrollment_bills'
  get "/enquiries/:enquiry_id/enrollments/new" => 'enrollments#new'
  post "/enquiries/:enquiry_id/enrollments" => 'enrollments#create'
  post "/enquiries/:enquiry_id/enrollments/safety_measures" => 'enrollments#safety_measures'
  
  # get '/enrollments/:enrollment_id/payment_masters' => 'payment_masters#index'
  # get '/enrollments/:enrollment_id/payment_masters/new' => 'payment_masters#new'
  # post '/enrollments/:enrollment_id/payment_masters' => 'payment_masters#create'
  # post '/enrollments/:enrollment_id/payment_masters/new_recurring_payment' => 'payment_masters#new_recurring_payment'
  # post '/enrollments/:enrollment_id/payment_masters/recurring_payment' => 'payment_masters#recurring_payment'
  # get '/enrollments/:enrollment_id/payment_masters/revise_care_giver_charge' => 'payment_masters#revise_care_giver_charge'
  # get '/enrollments/:enrollment_id/payment_masters/:id/payment_preview' => 'payment_masters#payment_preview'
  # put '/enrollments/:enrollment_id/payment_masters/:id/revoke_credit_note' => 'payment_masters#revoke_credit_note'
  # put '/enrollments/:enrollment_id/payment_masters/:id/issue_credit_note' => 'payment_masters#issue_credit_note'
  # put '/enrollments/:enrollment_id/payment_masters/:id/update_payment_mode_details' => 'payment_masters#update_payment_mode_details'
  # get '/enrollments/:enrollment_id/payment_masters/:id' => 'payment_masters#show'  

  resources :job_runs do
    collection do
      get "schedule_monthly_invoice"
    end
    member do
      get "mail_selected_payments"
      get "mail_all_payments"
      put "nullify_selected_payments"
    end
  end



  resources :service_masters
  resources :lost_reason_masters
  resources :enquiry_reference_masters
  resources :language_masters  

  resources :patient_selfcare_ability_masters
  resources :patient_adaptive_equipment_masters

  resources :key_vitals_masters
  
  resources :drug_masters
  
  resources :routine_masters
  
  resources :route_masters do
    collection do
      get :all_routes
    end
  end
  
  resources :form_masters
  
  resources :tickets do
    collection do 
      post :all_tickets
      get :all_patients
      get :all_care_givers
    end
  end
  
  resources :ticket_category_masters
  
  resources :ticket_conversations
  
  resources :daily_checks
  
  resources :unit_masters
  
  resources :patient_rate_masters
  
  resources :time_of_administrations


  devise_for :users, :controllers => {:registrations => 'registrations' , :sessions => 'sessions'}
  as :user do 
    get 'users/edit' => 'registrations#edit'
    put 'users' => 'registrations#update'
    get "authenticity" => "sessions#get_authenticity"
    get "get_current_user" => "sessions#get_current_user"
    get "check_user_exists" => "registrations#check_user_exists"
  end
  

  get "enquiry", :to => "home#welcome_enquiry"
  get "check_user_session", :to => "home#check_user_session"
  root to: "home#index"
  get "home/care_giver"
  get "home/services"
  get "home/team"
  get "home/foundation"
  get "home/news"
  get "home/careers"
  get "home/faq"
  resources :disability_masters 
  resources :new_city_requests do
    member do
      get :acknowledge
    end
  end

  get 'auto_search/autocomplete_drug_master_names'
  get 'auto_search/autocomplete_caregiver_master_names'
  get 'auto_search/autocomplete_patient_names'

  resources :enquiry_conversations do
    collection do
      get :conversation_json
      post :conversation_save
    end
  end

  resources :patients do
    collection do
      get :get_patient_details_with_user_id
      post :create_patient_from_user_params
      get :service
      get :list_care_givers
    end
  resources :enquiry_conversations  
  end  
  
  resources :email_templates do
    member do
      get :show_sms
      get :edit_sms
    end
  end

app/models/enrollment.rb
class Enrollment < ActiveRecord::Base
  WillPaginate.per_page = 10
  belongs_to :patient
  belongs_to :enrollment
  belongs_to :enquiry
  has_many :enquiry_care_givers, :foreign_key => "enquiry_id", :primary_key => "enquiry_id"
  belongs_to :super_care_giver, :class_name => "CareGiverMaster", :foreign_key => "super_care_giver_id"
  has_many :requested_time_slots, :foreign_key => "enquiry_id", :primary_key => "enquiry_id"
  has_many :patient_disabilities
  has_many :payment_masters
  has_many :patient_selfcare_abilities
  has_many :patient_adaptive_equipments
  has_many :vital_trends
  has_many :track_vitals
  has_many :drug_quantity_masters
  has_many :credit_notes
  has_many :patient_routines
  has_many :care_to_be_provided_plans
  has_many :requested_services
  has_many :care_giver_daily_attendances, :foreign_key => "enquiry_id", :primary_key => "enquiry_id"
  
  ENROLLMENT_FEE = ApplicationDefault.enrollment_fee
  CLOSE_REASONS = [['Patient Dead', "PATIENT_DEAD"], ['Other', "OTHER"]]
  NOTICE_PERIOD_DAYS_ON_PATIENT_DEAD = 3
  NOTICE_PERIOD_MAX_DAYS = 7
  
  scope :enrolled_on, lambda{|date| where("to_char(created_at,'DD-MM-YYYY' ) = '#{date.strftime('%d-%m-%Y')}'") }
  scope :active, lambda{where(:status => "ACTIVE")}
  scope :not_active, lambda{where("status != 'ACTIVE'")}
  scope :not_closed, lambda{where("status != 'CLOSED'")}
  scope :belongs_to_patient, lambda{|patient_id| where(:patient_id => patient_id)}
  scope :belongs_to_care_giver, lambda{|care_giver_id| where(:enquiry_id => EnquiryCareGiver.select(:enquiry_id).belongs_to_care_giver(care_giver_id))}
  scope :belongs_to_enquiry, lambda{|enquiry_ids| where(:enquiry_id => enquiry_ids)}

  attr_accessor :other_matching_care_givers
  
  def patient_with_address_html
    "<b>#{patient.name}</b>"
    "</br>"
    "#{patient.address.full_address_html}"
    "</br>"
    "#{enquiry.mobile_no}"
    "</br>"
    "#{enquiry.email}"
  end
  
  def payments_exists?
    @payment_exist ||= (payment_masters.not_failed.count > 0)
  end


  def valid_period_to_date(date)
    if(enquiry.service_required_to.present? and date > enquiry.service_required_to)
      enquiry.service_required_to
    elsif self.close_request_date.present?
      (self.close_request_date > date ? date : self.close_request_date )
    else
      date
    end
  end
  
  def closed?
    self.status == 'CLOSED'
  end

  def close_pending?
    self.status == 'CLOSE_PENDING'
  end

  def close_request_registered?
    close_request_date.present?
  end

  def notice_period_days_when_close_request_registered(date)
    return self.class::NOTICE_PERIOD_MAX_DAYS unless close_request_registered?
    diff = (date-close_request_date).to_i.abs
    ( diff > self.class::NOTICE_PERIOD_MAX_DAYS ? 0 : diff)
  end

  def reason_based_notice_period_days
    ((reason_for_closing.present? and reason_for_closing == 'PATIENT_DEAD') ? self.class::NOTICE_PERIOD_DAYS_ON_PATIENT_DEAD : self.class::NOTICE_PERIOD_MAX_DAYS)
  end

  def safety_measures
    violation_list = []
    female_caregiver =  enquiry.female_caregiver_required?
    violation_list.push("Female caregiver cannot assigned to the patient who lives alone") if (female_caregiver and patient_home_setting.to_s == "LIVES_ALONE")
    violation_list.push("Female caregiver cannot assigned to the patient who lives only with male") if (female_caregiver and patient_home_setting.to_s == "LIVES_ALONE")
    violation_list.push("Suffering from infectious disease ") if suffering_from_infection_disease
    violation_list.push("Locality is not saf/well conttected") if (female_caregiver and !safe_and_well_connected_locality)
    violation_list.push("Not provides personal protective equipment") if !provides_personal_protective_equipment
    violation_list.push("Assigned with Female caregiver and no patient family member helps") if (female_caregiver and !family_member_helps)
    violation_list
  end

  def cross_gender_request?
    enquiry.caregiver_gender.to_s != enquiry.care_giver_masters.first.try(:gender).to_s
  end

  def generate_payment_date_period
    start_date = nil
    end_date = nil
    existing_payments = payment_masters.order("created_at asc")
    start_date = (existing_payments.present? ? (existing_payments.last.period_to+1) : enquiry.service_required_from) 
    end_date = (enquiry.open_term? ? start_date.end_of_month : enquiry.service_required_to)
    (start_date..end_date)
  end

  def validate_and_revise_payment_generation_period(start_date, end_date)
    existing_payments = payment_masters.order("created_at asc")
    last_payment = existing_payments.last
    result = {:valid => true}
    existing_start_date = (existing_payments.present? ? (last_payment.period_to) : enquiry.service_required_from) 
    if existing_start_date > start_date or end_date <= start_date
      result[:valid] = false
      return result
    end
    result[:start_date] = start_date
    result[:end_date] = valid_period_to_date(end_date)
    result
  end
  
  def address_str
    address.try(:full_address)
  end
  
  
  
  def previous_due_amount
    payment_masters.inject(0){|sum, bill| sum+bill.total_pending_payment.to_i}.to_i.round
  end

  def as_json(options = nil)
    super(options)
  end
  
  def detail_json
    as_json({:include => {:patient => {:except => [:created_at, :updated_at], :methods => [:address_str]}, :enquiry => {:include => {:requested_services => {:except => [:created_at, :updated_at]}, :requested_time_slots => {:except => [:created_at, :updated_at], :methods => [:decorated_time_from, :decorated_time_to]}, :enquiry_languages => {:except => [:created_at, :updated_at]}, :enquiry_care_givers => { :include => {:care_giver_master => {:methods => [:name, :services, :languages]}}}}, :methods => [:patient_name, :locality, :services_str, :appointment_time_str , :address_str]}}})
  end

end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/views/enrollments/_care_givers_list.html.haml
%table.table-list
  - @enrollment.enquiry_care_givers.each do |enquiry_care_giver|
    %tr
    %td{:style => "vertical-align:top;"} 
      = image_tag enquiry_care_giver.care_giver_master.profile_pic.thumb.url
    %td{:style => "vertical-align:top;"} 
      %span.subHeader-clr= enquiry_care_giver.care_giver_master.name
    %td{:style => "vertical-align:top;"}= enquiry_care_giver.care_giver_master.telephone_no
    %td= enquiry_care_giver.care_giver_master.services_html.html_safe
    %td= enquiry_care_giver.care_giver_master.languages_html.html_safe
    - if @enrollment.closed?
      %td{:style => "vertical-align:top;"}  
        = link_to 'Closed' , '#'

    - else
      %td{:style => "vertical-align:top;"}  
        = link_to "Replace", change_care_giver_enrollment_path(@enrollment, :care_giver_master_id => enquiry_care_giver.care_giver_master_id), :class => "btn btn-danger"
      

app/views/enrollments/_close_details.html.haml
%table.table.table-list
  %thead
    %th Notification Date
    %th Notification Comments
    %th Requested Close Date
  %tbody
    %tr
      %td= @enrollment.notification_given_date
      %td= @enrollment.comments_on_notification
      %td= @enrollment.close_request_date
- if @enrollment.closed_date.present?
  %table.table.table-list
    %thead
      %th Closed Date
      %th Reason For Closing
      %th Closing Comments
    %tbody
      %tr
        %td= @enrollment.closed_date
        %td= @enrollment.reason_for_closing
        %td= @enrollment.closing_comments

app/views/enrollments/_enquiry_js_rendered.html.haml
%br
.row
  .sky-form
    .col-md-24
      .col-md-12
        .col-md-6
          %label
            Name:
            
        .col-md-12
          %label.input
            %input{:type => "text", :ng_model => "enrollment.enquiry.requested_user_name", :readonly => true}
      %br
      .col-md-12
        .col-md-6
          %label
            Appointment Time
        .col-md-12
          %label.input
            %input{:type => "text", :ng_model => "enrollment.enquiry.appointment_time_str", :readonly => true}
   
    .col-md-24
      .col-md-12
        .col-md-6
          %label
            Email:
            
        .col-md-12
          %label.input
            %input{:type => "text", :ng_model => "enrollment.enquiry.email", :readonly => true}
      %br
      .col-md-12
        .col-md-6
          %label
            Mobile No
        .col-md-12
          %label.input
            %input{:type => "text", :ng_model => "enrollment.enquiry.mobile_no", :readonly => true}
    .col-md-24
      %fieldset
        .col-md-12
          .col-md-6
            %label
              Address
          .col-md-12
            %label.textarea
              %textarea{:ng_model => "enrollment.enquiry.address_str", :readonly => true}
        .col-md-12
          = link_to "Modify Enquiry", "#", :ng_click => "modify_enquiry()", :class => "button"
%br
.row
  %table.table.table-list
    %thead
      %th Services
      %th Service From 
      %th Service To
      %th Registered By
    %tbody
      %tr
        %td {{enrollment.enquiry.services_str}}
        %td {{enrollment.enquiry.service_required_from}}
        %td {{enrollment.enquiry.service_required_to}}
        %td {{enrollment.enquiry.registered_by}}
%br
.row
  .col-md-10
    %table.table.table-list
      %tbody
        %tr
          %th No Of Caregivers
          %td {{enrollment.enquiry.no_of_care_givers}}
        %tr
          %th Require Heavy Patient Lifting?
          %td {{enrollment.enquiry.require_heavy_patient_lifting}}
        %tr
          %th Caregiver Stay
          %td {{enrollment.enquiry.caregiver_stay}}
        %tr
          %th Language Profficiency
          %td {{enrollment.enquiry.language_str}}
          
  .col-md-2
  .col-md-10
    %table.table.table-list
      %thead
        %th From Time
        %th To Time
      %tbody
        %tr{:ng_repeat => "time in enrollment.enquiry.requested_time_slots"}
          %td {{time.decorated_time_from}}
          %td {{time.decorated_time_to}}
.row
  #enquiryModificationDiv.custom-modal.modal.fade
    .modal-dialog.modal-lg
      .modal-content
        .modal-body
          %h4 
            %button{:class => "close", :data => {:dismiss => "modal"}, "area-label" => "close"}
              %span{"area-hidden" => "true"} 
                %i.fa.fa-close
          = render :partial => "modify_enquiry", :locals => {:after_enrollment => false}

app/views/enrollments/_patient_details.html.haml
.col-md-5
  %table.table.table-list
    %thead
      %th{:colspan => 2}
        Patient Details
    %tbody
      %tr
        %th Name
        %td= enrollment.patient.name 
      %tr
        %th Age 
        %td= enrollment.patient.age
      %tr
        %th Gender
        %td= enrollment.patient.gender
      %tr
        %th Complete address
        %td= enrollment.patient.address_str 
      %tr
        %th Mobile
        %td= enrollment.patient.mobile_no
      %tr
        %th Alternate No
        %td= enrollment.patient.alternate_contact_no
      %tr
        %th Nurse Manager
        %td= enrollment.super_care_giver.try(:name)
.col-md-2
.col-md-5
  %table.table.table-list
    %thead
      %th{:colspan => 2}
        Patient Next Kin Details
    %tbody
      %tr
        %th Name
        %td= enrollment.patient.guardian.name 
      %tr
        %th Relation with patient
        %td= enrollment.patient.guardian.relation  
      %tr
        %th Age
        %td= enrollment.patient.guardian.age  
      %tr
        %th Gender
        %td= enrollment.patient.guardian.gender  
      %tr
        %th Complete address
        %td= enrollment.patient.guardian.address_str
      %tr
        %th Mobile
        %td= enrollment.patient.guardian.mobile_no  
      %tr
        %th Alternate No
        %td= enrollment.patient.guardian.alternate_contact_no  
          
.col-md-23
  %table.table.table-list
    %tr
      %th Email For Official Communication
      %td= enrollment.email_for_official_comminication
      %th Primary Contact
      %td= enrollment.primary_contact

app/views/enrollments/change_plan.html.haml
= link_to 'BACK' , enrollment_path(@enrollment) , :class => 'btn btn-primary'
#lifeCircleAccordian.container{:ng_controller => "EnrollmentController", :ng_init => "changeEnrollmentPlan(#{@enrollment.id})"}
  .content_fullwidth
    .col-md-24
      .sky-form
        %header Change Enrollment Plan
      = render :partial => "modify_enquiry", :locals => {:after_enrollment => true}

app/views/enrollments/closed_form.html.haml
= render "closed_form"

app/views/enrollments/compare_payments_on_cg_transfer.html.haml
.col-md-12
  .col-md-4
    .row
      #caregiverBlock.row.sky-form
        %header Old Caregiver
        .col-md-5.col-xs-12
          = image_tag @old_care_giver_enquiry.care_giver_master.profile_pic.thumb.url, :class => "img-responsive img-thumbnail"
        .col-md-5
          .row
            .col-md-5.col-xs-6
              %span.subHeader Name
              %header-lg= @old_care_giver_enquiry.care_giver_master.name
              %span
                .subHeader-inline Age 
                .subHeader-clr= @old_care_giver_enquiry.care_giver_master.age
    .row
      %table.table-list
        %tr
          %th Caregiver Charge
          %td= @old_care_giver_enquiry.caregiver_charge
        %tr
          %th 
            = "Travel Charge for #{@old_care_giver_enquiry.approx_travel_distance} Kms"
          %td= @old_care_giver_enquiry.transport_charge

        %tr
          %th Total Charge
          %th= @old_care_giver_enquiry.total_charge
  .col-md-1
  .col-md-4
    .row
      #caregiverBlock.row.sky-form
        %header New Caregiver
        .col-md-5.col-xs-12
          = image_tag @new_care_giver_master.profile_pic.thumb.url, :class => "img-responsive img-thumbnail"
        .col-md-5
          .row
            .col-md-4.col-xs-6
              %span.subHeader Name
              %header-lg= @new_care_giver_master.name
              %span
                .subHeader-inline Age 
                .subHeader-clr= @new_care_giver_master.age
    .row.sky-form
      = form_for @new_enquiry_care_giver, :url => update_care_giver_transfer_enrollment_path(@enrollment) do |f|
        = f.hidden_field :old_enquiry_care_giver_id
        = f.hidden_field :care_giver_master_id
        %section
          %label.text
            New Caregiver Charge
          %label.input
            = f.number_field :caregiver_charge, autofocus: true 
        %section
          %label.text
            = "Transport Charge For #{f.object.approx_travel_distance} KM's"
          %label.input
            = f.number_field :transport_charge
        %section
          %label.text
            Total Charge
          %label.input
            = f.number_field :total_charge
        %section
          %label.text
            Adjustment Amount
          %label.input
            = f.text_field :adjustment_amount, :readonly => true
        %section
          %label.text
            Consider Modified Charge
          %label
            &nbsp;&nbsp;&nbsp;&nbsp;
            = f.check_box :consider_modified_charge
        %section
          %label.text
            Final Amount
          %label.input
            %input{:type => "text", :value => "#{f.object.total_charge + f.object.adjustment_amount}", :readonly => true}
        %footer
          .col-md-4
          .col-md-2
            = f.submit "Replace", :class => "button"

app/views/enrollments/new_notification.html.haml
.row
  .pull-right
    = link_to 'BACK' , enrollment_path(@enrollment) , :class => 'btn btn-primary'
.container
  .row
    = render "enrollments/enrollment_details"
  .row.sky-form
    = form_for(@enrollment, :url => post_notification_enrollment_path(@enrollment),:html => {:class => "sky-form"}) do |f|
      %fieldset
        %section
          .row
            %label.label.col.col-2 Notification Given On
            .col.col-8
              %label.input
                = f.text_field :notification_given_date, :readonly => true
        %section
          .row
            %label.label.col.col-2 Close On
            .col.col-8
              %label.input
                = f.text_field :close_request_date, :my_datepicker => true, :ng_model => "closeDate"
        %section
          .row
            %label.label.col.col-2 Notification Comments
            .col.col-8
              %label.textarea
                = f.text_area:comments_on_notification

        %section
          .row
            .col-md-4
            .col-md-3
              = f.submit "Save", :class => "button"

app/views/enrollments/transfer_care_giver.html.haml
.col-md-8
  - if @care_giver_masters.present?
    - @care_giver_masters.each_with_index do |care_giver, index|
      #caregiverBlock.row
        .col-md-2.col-xs-12
          = image_tag care_giver.image_url, :class => "img-responsive img-thumbnail"
        .col-md-9
          .row
            .col-md-4.col-xs-6
              %span.subHeader Name
              %header-lg= care_giver.name
              %span
                .subHeader-inline Age 
                .subHeader-clr= care_giver.age
              .subHeader
                .subHeader-inline References
                .subHeader-clr
              .subHeader
                %a{:href => "#collapse_#{index}", :data => {:toggle => "collapse"}, "aria-expanded" => "false", "aria-controls" => "collapse_{{$index}}"} 
                  Details 
                  %i.fa.fa-angle-down

            .col-md-3
              %span.subHeader Prof Qualification
              %header= care_giver.professional_qualification_html.html_safe

              %span.subHeader Approx Travel Distance
              %header= "#{care_giver.approximate_travel_distance} KM's"
            .col-md-3.pull-right
              %span.subHeader Charges
              %header-lg= care_giver.total_charge
              = form_tag compare_payments_on_cg_change_enrollment_path(@enrollment) do
                = hidden_field_tag :care_giver_master_id, care_giver.id
                = hidden_field_tag :old_care_giver_master_id, @old_care_giver_master_id
                = hidden_field_tag :approximate_travel_distance, care_giver.approximate_travel_distance
                = submit_tag "Assign", :class => "btn btn-success"
        .col-md-11
          %div{:class => "collapse", :id => "collapse_#{index}"}
            .panel.panel-default
              .panel-body
                .row
                  .col-md-4
                    %header Services
                    = care_giver.services_html.html_safe
                  .col-md-3
                    %header Language Profficiency
                    = care_giver.languages_html.html_safe
                  .col-md-3
                    %header Education
                    = care_giver.education_details_html.html_safe
                    %header ID Type
                    %ul.list1
                      %li
                        %i.fa.fa-chevron-circle-right
                        = care_giver.id_proof_type
  - else
    %p No Caregiver Mached
    //= '<script type="text/javascript"> window.close() </script>'.html_safe
    = link_to "Close", "#", :onclick => "window.close()"